sudo: required
services:
  - docker

before_install:
  - docker build -t sarath2991/supertramp:travis -f dockerfile.dev .

script:
  - docker run CI=true sarath2991/supertramp:travis npm run test -- --coverage

